<a href="https://colab.research.google.com/github/Ramyavenkatrajulu/Ramyavenkatrajulu/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
import numpy as np
np.version,np.show_config


(<module 'numpy.version' from '/usr/local/lib/python3.7/dist-packages/numpy/version.py'>,
 <function numpy.__config__.show>)

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
a = np.array([[1,2,3,3,4],[2,3,4,5,6]])
a.size, a.itemsize

(10, 8)

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
b = np.zeros(10)
b[4]=1
print(b)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
c = np.arange(10, 50)
print(c)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
print(c[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
np.arange(0,9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
d = np.array([1,2,0,0,4,0])
np.nonzero(d)


(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
np.random.rand(3,3,3)

array([[[4.83016367e-01, 2.11377508e-01, 2.97474835e-01],
        [5.05842189e-02, 3.41059297e-01, 4.33353989e-01],
        [4.87570458e-01, 3.33828387e-02, 9.62344309e-01]],

       [[7.10733890e-01, 3.53231370e-01, 2.87220978e-01],
        [3.12553135e-01, 4.28762503e-01, 4.08479722e-01],
        [3.61832487e-01, 2.23686529e-01, 3.49590435e-01]],

       [[8.61809391e-04, 8.48698162e-02, 3.52231802e-02],
        [3.59544466e-01, 9.79513217e-02, 4.54736007e-01],
        [5.72329488e-01, 4.59179457e-01, 2.79754225e-01]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
e = np.random.rand(10,10)
f, g = e.min(),e.max()
print(e)
print("Minimum and Maximum values are:", f, g)


[[0.8271186  0.88436885 0.40579957 0.3069935  0.4346801  0.97761252
  0.17484059 0.5484865  0.07992933 0.81908676]
 [0.07290337 0.38596481 0.4635403  0.67308092 0.48541341 0.86498731
  0.52331437 0.14694912 0.99149792 0.78159078]
 [0.39235712 0.82517863 0.82405076 0.80224041 0.80004807 0.89506901
  0.00247068 0.02252219 0.05884615 0.34717603]
 [0.29006626 0.95226604 0.77457623 0.57547238 0.52423196 0.01310318
  0.93576946 0.50148486 0.56833871 0.3042216 ]
 [0.62708372 0.18822232 0.03812654 0.258551   0.56677906 0.67402208
  0.93349083 0.55071576 0.63213028 0.61610661]
 [0.75012943 0.14867842 0.57139529 0.43619949 0.4064167  0.14953741
  0.69922623 0.87679979 0.18091475 0.76093586]
 [0.90496705 0.60786188 0.2461176  0.07470781 0.84755334 0.53078306
  0.13457242 0.16050027 0.15532218 0.25802155]
 [0.44270594 0.78162342 0.80532291 0.96142513 0.60799044 0.49934579
  0.00745536 0.2933564  0.71690012 0.05977486]
 [0.9872344  0.06622061 0.82179553 0.15539919 0.16487524 0.26908315
  0.23102625

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
h = np.random.rand(30)
#print(h)
print(np.mean(h))

0.5166631489158418


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
i = np.ones((5,5))
i[1:-1, 1:-1] = 0
print(i)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
j = np.arange(0, 9).reshape(3, 3)
j= np.pad(j,pad_width=1, mode='constant',constant_values=0)
print(j)

[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 3 4 5 0]
 [0 6 7 8 0]
 [0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
k = np.diag(1+np.arange(4),k=-1)
print(k)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
l = np.zeros((8,8),dtype = int)
l[1::2,::2] = 1
l[::2,1::2] = 1
print(l)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
m = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
m = np.random.random((5, 5))
n =(m- np.min(m))/(np.max(m))
print(n)

[[0.87300666 0.48052085 0.72556363 0.01890709 0.01703244]
 [0.08273319 0.40159329 0.5575996  0.63066163 0.89594629]
 [0.29575857 0.00245236 0.52524354 0.87635151 0.29849345]
 [0.72165193 0.15031913 0.76562898 0.         0.41763227]
 [0.93818242 0.76135145 0.35945854 0.99314435 0.89109583]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte), ("g", np.ubyte), ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
o = np.dot(np.ones((5,3)), np.ones((3,2)))
print(o)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
p = np.arange(11)
p[(3 < p) & (p <= 8)] *= -1
print(p)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
z**z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
p = np.random.uniform(-10,+10,10)
print(p)
print(np.copysign(np.ceil(np.abs(p)), p))

[-9.75265545 -7.17117371  0.80022376 -0.20084016  8.98362542 -6.37405216
  9.16211516 -9.12380995 -5.72622963  9.71847748]
[-10.  -8.   1.  -1.   9.  -7.  10. -10.  -6.  10.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a1 = np.arange(10,30)
print(a1)
a2 = np.arange(20,40)
print(a2)
print(np.intersect1d(a1,a2))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[20 21 22 23 24 25 26 27 28 29]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
q = np.seterr(all="ignore")
r = np.zeros(1)/0


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2022-06-30
2022-07-01
2022-07-02


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
july = np.arange('2022-07','2022-08', dtype='datetime64[D]')
print(july)

['2022-07-01' '2022-07-02' '2022-07-03' '2022-07-04' '2022-07-05'
 '2022-07-06' '2022-07-07' '2022-07-08' '2022-07-09' '2022-07-10'
 '2022-07-11' '2022-07-12' '2022-07-13' '2022-07-14' '2022-07-15'
 '2022-07-16' '2022-07-17' '2022-07-18' '2022-07-19' '2022-07-20'
 '2022-07-21' '2022-07-22' '2022-07-23' '2022-07-24' '2022-07-25'
 '2022-07-26' '2022-07-27' '2022-07-28' '2022-07-29' '2022-07-30'
 '2022-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
a = np.ones(3)*1
b = np.ones(3)*2

np.add(a,b,out=b)

np.divide(a,2,out=a)

np.negative(a,out=a)

np.multiply(a,b,out=a)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
q = np.zeros((5, 5))
q += np.arange(5)
print(q)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for i in range(10):
        yield i
v = np.fromiter(generate(),dtype=float,count=-1)
print(v)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
import numpy as np
w = np.linspace(0,1,11,endpoint=False)[1:]
print(w)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.rand(10)
print(x)
np.sort(x)

[0.9998376  0.16978494 0.75258685 0.89787446 0.4569175  0.13349106
 0.71144526 0.8458298  0.44743086 0.67594588]


array([0.13349106, 0.16978494, 0.44743086, 0.4569175 , 0.67594588,
       0.71144526, 0.75258685, 0.8458298 , 0.89787446, 0.9998376 ])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
y = np.arange(10)
print(y)
np.add.reduce(y)


[0 1 2 3 4 5 6 7 8 9]


45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
z1 = np.random.rand(10)
z2 = np.random.rand(10)
e = np.allclose(z1,z2)
print(e)
e1 = np.array_equal(z1, z2)
print(e1)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
n = np.ones(10)
n.flags.writeable = False
n[0] = 2

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
r = np.random.rand(10)
r[r.argmax()] = 0
print(r)

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions()
a = np.zeros((10,10))
print(a)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
b = np.arange(100)
c = np.random.uniform(0,100)
index = (np.abs(b-c)).argmin()
print(b[index])

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
C = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(C)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.58200806 0.81812055 0.94221323 0.94085571 0.63046818
  0.72243003 0.79126913 0.42625565 0.47459847]
 [0.58200806 0.         0.32434695 0.3613871  0.41341223 0.15350255
  0.4623364  0.41158149 0.54343635 0.68423047]
 [0.81812055 0.32434695 0.         0.34048079 0.5344881  0.44201358
  0.75455302 0.66554514 0.86527946 1.00505366]
 [0.94221323 0.3613871  0.34048079 0.         0.2243654  0.34820184
  0.5735401  0.44440384 0.82285924 0.96088555]
 [0.94085571 0.41341223 0.5344881  0.2243654  0.         0.31171177
  0.40373488 0.26209494 0.72155353 0.84847573]
 [0.63046818 0.15350255 0.44201358 0.34820184 0.31171177 0.
  0.31618435 0.2583914  0.47754641 0.6174672 ]
 [0.72243003 0.4623364  0.75455302 0.5735401  0.40373488 0.31618435
  0.         0.14218673 0.37145063 0.47346376]
 [0.79126913 0.41158149 0.66554514 0.44440384 0.26209494 0.2583914
  0.14218673 0.         0.49034318 0.60494349]
 [0.42625565 0.54343635 0.86527946 0.82285924 0.72155353 0.47754641
  0.37145063 0.490343

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
s = (np.random.rand(20)*100).astype(np.float32)
d = s.view(np.int32)
d[:] = s
print(s)

[2.66e-44 8.27e-44 1.30e-43 2.80e-44 4.48e-44 9.53e-44 7.85e-44 2.80e-44
 7.43e-44 3.22e-44 1.08e-43 9.39e-44 4.76e-44 1.40e-45 9.39e-44 7.57e-44
 8.13e-44 4.34e-44 3.36e-44 9.95e-44]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
a = np.genfromtxt(s, delimiter=",")
print(a)

[[ 1.  2.  3.  4.  5.]
 [ 6. nan nan  7.  8.]
 [nan nan  9. 10. 11.]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
n = np.arange(9).reshape(3,3)
print(n)
for index, value in np.ndenumerate(n):
    print(index, value)
for index in np.ndindex(n.shape):
    print(index, n[index])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
g = np.zeros((n,n))
np.put(g, np.random.choice(range(n*n), p, replace=False),1)
print(g)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
b = np.random.rand(5,10) 
print(b)
c = b-b.mean(axis=1, keepdims=True)
print(c)

[[0.28873405 0.31773676 0.86787413 0.34291632 0.22855149 0.32241496
  0.81383105 0.18744678 0.48590674 0.20143645]
 [0.47033503 0.76070736 0.68952761 0.75669897 0.58809464 0.24652649
  0.92787852 0.7660592  0.28057517 0.77969008]
 [0.56346519 0.34587471 0.46503346 0.60023439 0.5697885  0.97579905
  0.62763529 0.04758012 0.92697543 0.98938352]
 [0.07486347 0.65490836 0.75472256 0.03515254 0.95113469 0.58773145
  0.49043836 0.98335793 0.09233946 0.656462  ]
 [0.3027269  0.49805222 0.51964837 0.72214186 0.06994684 0.15351199
  0.695336   0.63047306 0.38626348 0.19925799]]
[[-0.11695082 -0.08794812  0.46218926 -0.06276855 -0.17713338 -0.08326991
   0.40814618 -0.21823809  0.08022187 -0.20424843]
 [-0.15627428  0.13409805  0.0629183   0.13008966 -0.03851466 -0.38008282
   0.30126922  0.13944989 -0.34603413  0.15308077]
 [-0.04771177 -0.26530226 -0.14614351 -0.01094258 -0.04138847  0.36462208
   0.01645833 -0.56359685  0.31579846  0.37820656]
 [-0.45324761  0.12679727  0.22661148 -0.49295854

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
a = np.array([[11,10,5],[9,5,2]])
print(a)
print(a[a[:,1].argsort()])

[[11 10  5]
 [ 9  5  2]]
[[ 9  5  2]
 [11 10  5]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
d = np.random.randint(0,3,(3,10))
print(d)
print((~d.any(axis=0)).any())


[[1 2 0 0 2 2 2 0 1 2]
 [0 2 1 1 2 1 0 2 0 1]
 [1 0 0 1 2 2 1 1 1 2]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
p = np.random.uniform(0,1,10)
print(p)
n = 0.5

m = p.flat[np.abs(p - n).argmin()]
print(m)

[0.89205164 0.18431072 0.8423971  0.03868202 0.69327374 0.53736498
 0.13479493 0.03475399 0.23345405 0.00563976]
0.5373649765147687


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
a = np.arange(3).reshape(1,3)
#print("a is", a)
b= np.arange(3).reshape(3,1)
#print(b)
it = np.nditer([a,b,None])
for i,j,k in it: k[...] = i + j
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
print(I)
np.add.at(Z, I, 1)
print(Z)

[3 0 2 7 5 6 6 6 4 4 6 9 3 0 8 7 0 2 6 1]
[4. 2. 3. 3. 3. 2. 6. 3. 2. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
import numpy as np

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
print(I)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

[[[1 3 2]
  [3 1 0]
  [3 2 0]
  ...
  [1 3 0]
  [0 1 3]
  [2 0 3]]

 [[3 1 1]
  [3 2 0]
  [1 2 3]
  ...
  [1 0 3]
  [3 1 3]
  [2 0 2]]

 [[3 0 3]
  [0 2 1]
  [3 0 2]
  ...
  [0 2 1]
  [3 1 1]
  [0 3 0]]

 ...

 [[2 2 0]
  [3 1 2]
  [2 0 1]
  ...
  [0 3 0]
  [0 1 0]
  [2 3 0]]

 [[2 3 3]
  [1 2 3]
  [1 1 3]
  ...
  [3 0 3]
  [2 2 3]
  [2 0 0]]

 [[0 0 3]
  [2 3 1]
  [2 2 0]
  ...
  [1 0 0]
  [3 3 1]
  [0 1 2]]]
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
f = np.random.randint(0,10,(3,4,3,4))
print(f)
s = f.sum(axis=(-2,-1))
print(s)

[[[[7 0 6 2]
   [7 3 0 6]
   [8 9 6 6]]

  [[2 8 7 6]
   [6 9 2 0]
   [6 8 0 2]]

  [[3 3 2 4]
   [6 6 7 0]
   [7 9 1 7]]

  [[7 0 1 0]
   [7 9 7 7]
   [1 1 7 3]]]


 [[[1 5 3 2]
   [8 4 2 7]
   [0 6 4 3]]

  [[4 0 6 3]
   [9 5 5 8]
   [3 7 5 2]]

  [[5 4 9 3]
   [4 6 3 2]
   [9 1 4 1]]

  [[4 5 3 7]
   [8 8 3 3]
   [3 9 1 4]]]


 [[[5 2 1 1]
   [5 8 7 6]
   [3 7 8 6]]

  [[5 7 3 2]
   [5 1 0 9]
   [3 4 0 1]]

  [[7 3 1 6]
   [0 7 3 4]
   [9 7 9 7]]

  [[1 9 8 0]
   [1 2 4 9]
   [2 4 4 8]]]]
[[60 56 55 50]
 [45 57 51 58]
 [59 40 63 52]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.11637187, 1.27816249, 1.20856356, 1.15857131, 0.74759339])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
v = np.array([1,2,3,4,5])
n = 3
d = np.zeros(len(Z) + (len(Z)-1)*(n))
#print(d)
d[::4] = v
print(d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
d = np.ones((5,5,3))
#print(d)
e = 2*np.ones((5,5))
#print(e)
print(d*e[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
s1 = np.arange(25).reshape(5,5)
print(s1)
s1[[0,1]]= s1[[1,0]] 
print(s1)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,2,3,4,5,6,7])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 2 3 4 5 6 7]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
n = np.random.randint(0,2,100)
print(n)
np.logical_not(n, out=n)

[0 1 1 1 1 1 1 0 1 1 1 1 0 0 0 1 1 0 1 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 0 1
 1 0 0 1 0 0 1 0 0 1 1 0 1 0 1 1 1 0 1 0 1 1 1 0 0 1 1 0 1 1 1 1 0 0 1 0 1
 0 0 0 1 0 0 1 0 1 1 1 0 0 1 1 1 0 1 1 0 0 1 0 0 0 0]


array([1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
f = np.random.randint(0,10,30)
print(f)
print(np.bincount(f).argmax())

[0 3 1 2 2 8 3 3 7 8 9 7 6 8 8 3 5 8 3 6 0 4 0 1 5 1 0 4 7 6]
3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
import numpy as np
as_strided = np.lib.stride_tricks.as_strided
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 2 2]
   [0 0 4]
   [1 4 1]]

  [[2 2 3]
   [0 4 4]
   [4 1 3]]

  [[2 3 4]
   [4 4 4]
   [1 3 4]]

  [[3 4 4]
   [4 4 1]
   [3 4 4]]

  [[4 4 3]
   [4 1 1]
   [4 4 3]]

  [[4 3 3]
   [1 1 3]
   [4 3 0]]

  [[3 3 4]
   [1 3 3]
   [3 0 4]]

  [[3 4 2]
   [3 3 2]
   [0 4 4]]]


 [[[0 0 4]
   [1 4 1]
   [2 4 0]]

  [[0 4 4]
   [4 1 3]
   [4 0 0]]

  [[4 4 4]
   [1 3 4]
   [0 0 4]]

  [[4 4 1]
   [3 4 4]
   [0 4 1]]

  [[4 1 1]
   [4 4 3]
   [4 1 2]]

  [[1 1 3]
   [4 3 0]
   [1 2 1]]

  [[1 3 3]
   [3 0 4]
   [2 1 3]]

  [[3 3 2]
   [0 4 4]
   [1 3 1]]]


 [[[1 4 1]
   [2 4 0]
   [1 1 4]]

  [[4 1 3]
   [4 0 0]
   [1 4 0]]

  [[1 3 4]
   [0 0 4]
   [4 0 3]]

  [[3 4 4]
   [0 4 1]
   [0 3 1]]

  [[4 4 3]
   [4 1 2]
   [3 1 2]]

  [[4 3 0]
   [1 2 1]
   [1 2 3]]

  [[3 0 4]
   [2 1 3]
   [2 3 3]]

  [[0 4 4]
   [1 3 1]
   [3 3 2]]]


 [[[2 4 0]
   [1 1 4]
   [0 0 4]]

  [[4 0 0]
   [1 4 0]
   [0 4 3]]

  [[0 0 4]
   [4 0 3]
   [4 3 2]]

  [[0 4 1]
   [0 3 1]
   [3 2 4]]

  [[4 1 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
z = np.ones((16,16))
k=4
s = np.add.reduceat(np.add.reduceat(z, np.arange(0, z.shape[0], k), axis=0),np.arange(0, z.shape[1], k), axis=1)
print(s)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 10
print (Z[np.argsort(Z)[-n:]])

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Good", 1.5, 3),
              ("Morning", 2.3, 2)])
print(Z)
y = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(y)

[['Good' '1.5' '3']
 ['Morning' '2.3' '2']]
[(b'Good', 1.5, 3) (b'Morning', 2.3, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
Z = np.random.rand(int(5e7))

%timeit np.power(Z,3)
%timeit Z*Z*Z
%timeit np.einsum('i,i,i->i',Z,Z,Z)

1 loop, best of 5: 3.69 s per loop
10 loops, best of 5: 138 ms per loop
10 loops, best of 5: 122 ms per loop


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 4 0]
 [1 4 3]
 [3 3 0]
 [3 4 1]
 [3 1 3]
 [2 4 2]
 [0 1 0]
 [1 3 0]
 [0 1 0]
 [4 2 3]]
[[2 4 0]
 [1 4 3]
 [3 3 0]
 [3 4 1]
 [3 1 3]
 [2 4 2]
 [0 1 0]
 [1 3 0]
 [0 1 0]
 [4 2 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)   
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 

array([0.02091998, 0.59164523, 0.34698414, 0.63150242, 0.00092991,
       0.20642474, 0.119511  , 0.06026653, 0.17866469, 0.05758462])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
import numpy as np
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100)
#print(X)
N = 1000 
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.3133429  0.0849153]
